# Exerci­cio 3(a)

In [4]:
import numpy as np

rng = np.random.default_rng(seed=0)
x = np.array([[3, 2, 5, 7, 8, 9, 1, 4, 5]]).T
eps = rng.normal(size=x.shape)
y = 0.77 + 0.15 * x - 1.22 * (x ** 2) + 0.89 * (x ** 3) + eps

var1 = ((x - x.mean()) * (y - y.mean())).sum() / ((x - x.mean()) ** 2).sum() #beta1 ?
print(var1)
var2 = y.mean() - var1 * x.mean() #beta0 ?
print(var2)
var3 = var2 + var1 * x #y_hat, estimador para y
print(var3)
var4 = ((var3 - y) ** 2).mean() #MSE, erro médio quadrático.
print(var4)

66.4303221275964
-168.92355044829358
[[  30.36741593]
 [ -36.06290619]
 [ 163.22806019]
 [ 296.08870444]
 [ 362.51902657]
 [ 428.9493487 ]
 [-102.49322832]
 [  96.79773806]
 [ 163.22806019]]
5218.275201555755


Resposta: O método implementado é uma regressão linear. O pesquisador realiza uma regressão linear em cima dos pontos de uma curva polinomial de grau 3. Ele calcula os paramêtros da regressão linear, beta 1 e beta 0, em seguida calcula o valor estimado para esses ponto, y_hat (y chapéu), e por fim calcula o erro médio quadrático dessa estimação.

# Exercicio 3(b)

O método não é adequado, pois regressão linear é um modelo polinomial de grau 1, enquanto o problema original era um polinomio de grau 3.O pesquisador deve esperar que var4, o erro médio quadrático, seja alto.

# Exercicio 3(c)

In [27]:
xx = np.concatenate([np.ones(x.shape), x, x ** 2, x ** 3], axis=1)
print(xx)
print(xx.T)
print(y.shape)
print(y)
var5 = np.linalg.inv(xx.T @ xx) @ xx.T @ y # beta hat. Estima o vetor beta hat através dos mínimos quadrados que minimiza o erro residual.
var6 = xx @ var5 # y_hat. Estimador de y
var7 = ((var6 - y) ** 2).mean() #MSE, erro médio quadrático.

print('-'*20)
print(var5.shape)
print('-'*20)
print(var6)
print('-'*20)
print(var7)

[[  1.   3.   9.  27.]
 [  1.   2.   4.   8.]
 [  1.   5.  25. 125.]
 [  1.   7.  49. 343.]
 [  1.   8.  64. 512.]
 [  1.   9.  81. 729.]
 [  1.   1.   1.   1.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  3.   2.   5.   7.   8.   9.   1.   4.   5.]
 [  9.   4.  25.  49.  64.  81.   1.  16.  25.]
 [ 27.   8. 125. 343. 512. 729.   1.  64. 125.]]
(9, 1)
[[ 14.39573022]
 [  3.17789514]
 [ 82.91042265]
 [247.41490012]
 [379.03433063]
 [552.47159505]
 [  1.89400005]
 [ 39.75708096]
 [ 81.56626476]]
--------------------
(4, 1)
--------------------
[[ 14.60346809]
 [  3.89452318]
 [ 82.30774154]
 [247.28053177]
 [379.57512266]
 [552.18584512]
 [  1.50370508]
 [ 38.96354061]
 [ 82.30774154]]
--------------------
0.2937692716528738


In [21]:
xx = np.concatenate([np.ones(x.shape), x], axis=1)
var5 = np.linalg.inv(xx.T @ xx) @ xx.T
print(var5.shape)

(2, 9)


# Exercicio 4

In [8]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA
from sklearn.linear_model import LogisticRegression as LR
from sklearn.naive_bayes import GaussianNB as NB
from sklearn.neighbors import KNeighborsClassifier as kNN
from sklearn import preprocessing

df = pd.read_csv("./soccer.csv")

X = df.drop("target", axis=1)
y = df[["target"]]

X_train, y_train = X.iloc[:2560], y.iloc[:2560]
X_test, y_test = X.iloc[2560:], y.iloc[2560:]

X_train.head(10)

home_team    away_team  rank_dif  goals_dif  goals_dif_l5  goals_suf_dif  \
0    Barbados         Cuba     -21.0        2.0           2.0       1.000000   
1    Barbados         Cuba     -21.0        1.0           1.0       0.500000   
2    Mongolia         Guam      -4.0        4.0           4.0      -1.000000   
3       Nepal       Bhutan     -22.0        1.0           1.0       0.000000   
4  Bangladesh     Pakistan      -7.0       -1.0          -1.0      -0.500000   
5    Pakistan       Bhutan      18.0        1.0           1.0      -2.000000   
6  Bangladesh        Nepal      33.0       -1.5          -1.5      -0.666667   
7      France  Netherlands     -16.0       -2.0          -2.0      -1.000000   
8     Ukraine     Slovakia       9.0       -1.0          -1.0       1.000000   
9     Denmark        Wales     -10.0       -4.0          -4.0       2.000000   

   goals_suf_dif_l5  goals_per_ranking_dif  dif_rank_agst  dif_rank_agst_l5  \
0          1.000000               0.037037     -92.000000        -92.000000   
1          0.500000               0.008511     -35.500000        -35.500000   
2         -1.000000               0.021622       0.000000          0.000000   
3          0.000000               0.004975       7.000000          7.000000   
4         -0.500000              -0.007200      30.500000         30.500000   
5         -2.000000               0.005634       0.000000          0.000000   
6         -0.666667              -0.007884       2.666667          2.666667   
7         -1.000000              -0.100000      -5.000000         -5.000000   
8          1.000000              -0.287879      35.000000         35.000000   
9          2.000000              -0.137931      -3.000000         -3.000000   

   dif_points_rank  dif_points_rank_l5  is_friendly_1  
0         0.018519            0.018519              1  
1         0.008897            0.008897              1  
2         0.016216            0.016216              0  
3         0.000000            0.000000              0  
4        -0.010437           -0.010437              0  
5         0.009317            0.009317              0  
6         0.002243            0.002243              0  
7        -0.083333           -0.083333              0  
8        -0.265152           -0.265152              0  
9        -0.103448           -0.103448              0

In [9]:
print(X_train["dif_rank_agst"].max(), X_train["dif_rank_agst"].min())
print(X_train["goals_dif"].max(), X_train["goals_dif"].min())

129.25 -182.0
5.166666666666667 -5.0


In [14]:
X_train = X_train.drop(["home_team", "away_team"], axis=1)
X_test = X_test.drop(["home_team", "away_team"], axis=1)

scaler = preprocessing.StandardScaler().fit(X_train)
X_train = preprocessing.scale(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_test.head(10)

home_team          away_team  rank_dif  goals_dif  goals_dif_l5  \
2560        Morocco            Comoros    -104.0   0.781250           0.2   
2561          Gabon              Ghana      37.0  -0.090686           0.2   
2562    South Korea            Iceland     -29.0   0.647619           0.2   
2563        Nigeria              Sudan     -89.0   0.401434           1.0   
2564  Guinea-Bissau              Egypt      61.0  -0.770690          -0.8   
2565       Colombia           Honduras     -60.0  -0.059553          -0.6   
2566           Peru             Panama     -41.0  -0.427381           0.0   
2567        Algeria  Equatorial Guinea     -85.0   1.325000           0.6   
2568         Gambia               Mali      97.0  -0.511905          -1.4   
2569        Tunisia         Mauritania     -73.0   0.689793           0.2   

      goals_suf_dif  goals_suf_dif_l5  goals_per_ranking_dif  dif_rank_agst  \
2560      -0.912202              -0.4               0.013097     -30.389881   
2561       0.443627               0.2              -0.003208      15.752451   
2562      -1.080952              -0.6               0.004299      17.052381   
2563      -0.573477              -1.6               0.007106     -21.334528   
2564       0.998276               0.8              -0.007272      -7.724138   
2565      -0.650951              -1.8               0.023644     -34.928040   
2566      -0.048810              -1.0               0.017658     -41.533333   
2567      -0.530435               0.2               0.018797     -20.204348   
2568       0.226190               1.2              -0.008401      26.214286   
2569      -0.539872               0.0               0.008609      -1.394737   

      dif_rank_agst_l5  dif_points_rank  dif_points_rank_l5  is_friendly_1  
2560             -68.6         0.025636            0.030096              0  
2561              15.6        -0.002582           -0.004016              0  
2562             -26.0         0.015580            0.026649              1  
2563              18.0         0.027568            0.022632              0  
2564              30.8        -0.013644           -0.011007              0  
2565             -24.0         0.071754            0.121231              1  
2566              -4.4         0.048008           -0.018429              1  
2567             -26.2         0.036003            0.013393              0  
2568              31.6        -0.004160           -0.034131              0  
2569             -35.2         0.021845            0.016958              0

# 4(a)

É necesário normalizar as features porque elas apresentam escalas diferentes. Por exemplo, a variável diferença entre ranking médio do time da casa e do time fora de fora, isto é _dif_rank_agst_, possui uma escala diferente diferença da média de gols entre o time da casa e o de fora, _goals_dif_. Ao não se usar features normalizadas, o modelo pode atribuir valores desproporcionais aos parâmetros aprendidos, deixando a variável com escala maior dominar os resultados do modelo, e portanto, diminuindo a contribuição das outras variáveis.

## 

## 4(b)



In [17]:
neigh = kNN(n_neighbors=5)
neigh.fit(X_train, y_train)

/home/thiago/python-envs/base/lib/python3.10/site-packages/sklearn/neighbors/_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [25]:
y_hat_train = neigh.predict(X_train)
y_hat_test = neigh.predict(X_test)

# train_error = ((y_hat_train - y_train).mean()) ** 2
# test_error = ((y_hat_test - y_test).mean()) ** 2
print(y_hat_test.shape, y_test.shape)

(640,) (640, 1)


In [41]:
train_error = (((y_hat_train - y_train["target"].to_numpy())) ** 2).mean()
test_error = (((y_hat_test - y_test["target"].to_numpy())) ** 2).mean()

In [42]:
print(train_error)
print(test_error)

0.23203125
0.365625


# Fazer (c) e (d)

# Exercicio 5

# 5(a)

O modelo que necessita da normalização é o lasso. Como se trata de um método de regularização, ele penaliza os coeficientes maiores, logo se as features não tiverem uma escala parecida, alguma variável pode ser mais penalizada incorretamente.